### ISSUE TITLE
2.0 missing on the release site

### ISSUE THREAD

**Issue by Mailaender** [bneijt/autotrash#10]
http://www.logfish.net/pr/autotrash/downloads/ only has a 1.5 tarball. Is that on purpose?

**Comment by bneijt** [comment]
Yes,

I'm thinking of retiring the whole logfish domain and moving downloads to
github and bneijt.nl.

I will put up a notice on the download page.

Thank you for pointing this out!

**Comment by bneijt** [comment]
I've updated the downloads page, downplayed the logfish homepage and linked to github for the downloads.

I'll be moving the page in the near future and update all references to the logfish.net homepage.

Thank you for reporting!
