### ISSUE TITLE
autotrash: error: no such option: -t

### ISSUE THREAD

**Issue by SiqingYu** [bneijt/autotrash#13]
OS: Ubuntu 16.04.3 LTS
When I run this command:
`autotrash -td 30`

It shows an error:
```
Usage: autotrash -d <days of age to purge>

autotrash: error: no such option: -t
```

**Comment by bneijt** [comment]
Could you post the `autotrash --help` and `autotrash --version` output?

**Comment by SiqingYu** [comment]
Version 0.1.5
Copyright (C) 2008 A. Bram Neijt <bneijt@gmail.com>
License GPLv3+

**Comment by SiqingYu** [comment]
Usage: autotrash -d <days of age to purge>

Options:
  -h, --help            show this help message and exit
  -d DAYS, --days=DAYS  delete files older then DAYS number of days.
  -T PATH, --trash-path=PATH
                        set Trash path to PATH. Default: ~/.local/share/Trash
  --max-free=M          only run if less then M megabytes of free space is
                        left.
  --delete=M            delete at least M megabytes.
  --min-free=M, --keep-free=M
                        set --delete to make use M megabytes of space is
                        available.
  -D REGEX, --delete-first=REGEX
                        push files matching this REGEX to the top of the
                        deletion queue
  -v, --verbose         be more verbose, a must when testing something out
  -q, --quiet           only output warnings
  --check               report .trashinfo files without a real file
  --dry-run             just list what would have been done
  --stat                show the number, and total size of files involved
  -V, --version         show version and exit

**Comment by bneijt** [comment]
The lowercase `-t` option is only available in a newer version of autotrash, here is the help of `0.2.1
`:

    Usage: autotrash -d <days of age to purge>
    Options:
      -h, --help            show this help message and exit
      -d DAYS, --days=DAYS  delete files older then DAYS number of days.
      -T DIRECTORY, --trash-path=DIRECTORY
                            empty the trash path in the given DIRECTORY instead of
                            using the user home directory
      -t, --trash-mounts    Process all user trash directories instead of just the
                            one in the home directory
      --max-free=M          only run if less then M megabytes of free space is
                            left.
      --delete=M            delete at least M megabytes.
      --min-free=M, --keep-free=M
                            set --delete to make sure M megabytes of space is
                            available.
      -D REGEX, --delete-first=REGEX
                            push files matching this REGEX to the top of the
                            deletion queue
      -v, --verbose         be more verbose, a must when testing something out
      -q, --quiet           only output warnings
      --check               report .trashinfo files without a real file
      --dry-run             just list what would have been done
      --stat                show the number, and total size of files involved
      -V, --version         show version and exit
