### ISSUE TITLE
Date parse error for info files

### ISSUE THREAD

**Issue by antofthy** [bneijt/autotrash#15]
Verion Rehat Enterprise 7 RPM   autotrash-0.1.5-2.el7
This appears to be the same as the current github version (15)

However it errors while cleaning up trash generated by a debian environment....

  File "/bin/autotrash", line 317, in <module>
    sys.exit(main(sys.argv))
  File "/bin/autotrash", line 251, in main
    file_time = trash_info_date(file_name)
  File "/bin/autotrash", line 101, in trash_info_date
    return time.strptime(parser.get(section, key), '%Y-%m-%dT%H:%M:%S')
  File "/usr/lib64/python2.7/_strptime.py", line 467, in _strptime_time
    return _strptime(data_string, format)[0]
  File "/usr/lib64/python2.7/_strptime.py", line 328, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains: .710Z

**Comment by bneijt** [comment]
I have not yet seen this locally, but I guess I could add support for a time format with nanoseconds and timezone information appended :thinking: I'm opening a branch to see if I can fix this with `dateutil.parser`

**Comment by antofthy** [comment]
Example trash info file that it fails to parse...
Info filename...  44f9088e-87c8-4cc3-8915-18fd675458ec.trashinfo
Contents
```
[Trash Info]
Path=/home/user/public_html/webAppDev/week10/.env
DeletionDate=2019-08-27T05:20:31.377Z
```

**Comment by bneijt** [comment]
Busy times, sorry.

I refactored the code in the https://github.com/bneijt/autotrash/tree/issue-15 branch. I'll do some more testing later, but if you want you could already experiment with that branch.

**Comment by antofthy** [comment]
When do you think the update will be available in an RPM?

**Comment by bneijt** [comment]
You will have to contact the downstream package maintainer to see when and if that package is going to be updated.
In the meantime, validate that this fix works by using:
```
pip install --user autotrash
export PATH=$PATH:$HOME/.local/bin
which autotrash
```
The last command should output that you have `autotraash` installed in your users `.local/bin` folder.

**Comment by antofthy** [comment]
Syntax error...

*pip install --user autotrash*
*...*
*.local/bin/autotrash  --help*

Traceback (most recent call last):
  File ".local/bin/autotrash", line 7, in <module>
    from autotrash.app import main
  File
"/home/anthony/.local/lib/python2.7/site-packages/autotrash/__init__.py",
line 8, in <module>
    from .app import *
  File "/home/anthony/.local/lib/python2.7/site-packages/autotrash/app.py",
line 104
    def read_datetime(value: str) -> datetime.datetime:
                           ^
SyntaxError: invalid syntax

**Comment by bneijt** [comment]
That does not look good. What version op python are you using? `python --version` ?

**Comment by bneijt** [comment]
This is because of type hints missing in python 2+.
Because python 2 is end of life, I'm setting the minimum python version for the package to 3.5

Try `pip3 install --user autotrash`

[1] https://pythonclock.org/

**Comment by antofthy** [comment]
Thank you.  I am still learning python.

**Comment by antofthy** [comment]
I finally got to install and test....
Yeah it is handling things fine now... lts hope it gets into the up-stream providers quickly

**Comment by antofthy** [comment]
Just as an update.   It is now working as expected with the application
that creates timestamped with micro seconds.

Thank you.
