### ISSUE TITLE
Installing on Linux Mint 20 / Ubuntu 20.04 LTS (Focal Fossa)

### ISSUE THREAD

**Issue by NicoWeio** [bneijt/autotrash#24]
I noticed that **autotrash** is not in the Ubuntu _20.04LTS/focal_ package repo (but in e.g. [_bionic_](https://packages.ubuntu.com/bionic/autotrash)). Is it because of your [new packaging approach](https://github.com/bneijt/autotrash/releases/tag/v0.3.0), and shouldn't the Installation section in README be updated to reflect this?

**Comment by bneijt** [comment]
I'm not really sure what you mean yet. Could you elaborate on these points?
Is there a way to change the packaging approach to also end up in bionic?

**Comment by NicoWeio** [comment]
Okay, I'll try and elaborate on that. Please note that I hardly know anything about packaging etc. 
So I installed _autotrash_ back on Linux Mint 19, but the upgrade to Linux Mint 20 meant switching to a newer Ubuntu package base, i.e. _focal_. In that package base, autotrash_ is no longer available. I uninstalled it for a safe upgrade, but now I can't easily reinstall using the package manager. 
Looking at this repository, I concluded that you, @bneijt, are not in charge of packaging. [This page](https://packages.ubuntu.com/xenial/autotrash) suggests that the package maintainers are _Ubuntu MOTU Developers_ or rather _Lorenzo De Liso_. So should I ask them/him instead?

> Is there a way to change the packaging approach to also end up in bionic?

I'm not sure if I understood that correctly. I don't think it's a huge deal to update the _.deb_ package to install _autotrash_ in its new, modular form. But somebody has to do it. Preferably the one who did it last time. 

So I guess I should contact _Lorenzo De Liso_ directly?

**Comment by maximus499** [comment]
@bneijt 
I have the same issue. My system is Linux Mint 20, and it is based on Ubuntu 20.04 LTS. When I run 
`sudo apt-get install autotrash` I get an error and it's 

`Package autotrash is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'autotrash' has no installation candidate`

How could I fix it?

**Comment by bneijt** [comment]
If you want to install it via the package repository of your distribution, you will have to find a maintainer there to package and distribute it. @NicoWeio is right in that I don't have access or rights to publish packages in the different distributions.

For now, you could use `pip install autotrash` to install an executable in `~/.local/bin` for your user.

Let me know if that work-around works and if you want it to be part of the Ubuntu distribution, consider opening a ticket there.

**Comment by bneijt** [comment]
I'm closing this issue due to lack of progress and the actual freature request being out of scope. I have added a packaging directory, so feel free to add linux mint package build scripts in a `mint` directory below the `packaging` directory if you feel so inclined.
