### ISSUE TITLE
[Suggestion] Add to AUR

### ISSUE THREAD

**Issue by MithicSpirit** [bneijt/autotrash#29]
It would be nice if autotrash was added to the [Arch User Repository](https://aur.archlinux.org/) (or even better would be the main Archlinux repos). I know that it can just be installed with pip but I (and I think most other people) prefer to have most things on a single package manager rather than a ton of different ones.

**Comment by bneijt** [comment]
An example of an Arch package is now at https://github.com/bneijt/autotrash/tree/master/packaging/arch

I have not yet gone through the "trouble" of registering this in aur, feel free to do so if you would like to be maintainer of the package.

I'm closing this for now, as it is now possible to download the pkgbuild and run `makepkg` next to it. Registration in AUR is something I may consider in the future but do not have time for at this moment.

Thank you for your suggestion!

**Comment by MithicSpirit** [comment]
I finally got around to adding the package to the AUR: https://aur.archlinux.org/packages/autotrash/
I'll try to keep it up-to-date but I can also add you as a co-maintainer if you so desire (you're already listed as one at the top of the `PKGBUILD`). 
The only differences between the AUR package and the `packaging/arch` folder are that I added myself as a maintainer and disguised your email in the `PKGBUILD`, and created a `.SRCINFO`.

**Comment by bneijt** [comment]
Thank you for your support! I have removed the PKGBUILD info from the main branch and pointed to the package in the README.
