### ISSUE TITLE
Hidden files are not removed (. files)

### ISSUE THREAD

**Issue by bneijt** [bneijt/autotrash#3]
Hidden files are not seen by the glob module, which means that hidden files are never removed from the trash.

**Comment by alextoind** [comment]
Any workaround for this issue?

**Comment by bneijt** [comment]
This issue is closed, are you experiencing this issue?
Could you let me know the version of autotrash that you are experiencing this issue with?
 (`autotrash --version`)

**Comment by alextoind** [comment]
Maybe that's the problem: I've installed it through Ubuntu (Xenial) PPA:

```
$ autotrash --version
Version 0.1.5
Copyright (C) 2008 A. Bram Neijt <bneijt@gmail.com>
License GPLv3+

$ apt policy autotrash 
autotrash:
  Installed: 0.1.5-1.1
  ...
```
