### ISSUE TITLE
Arrow dependency unnecessary?

### ISSUE THREAD

**Issue by hanmertens** [bneijt/autotrash#35]
Both [`setup.cfg`](https://github.com/bneijt/autotrash/blob/5496bd9fca032b9c2f4329f5c136e2ca13af2b8b/setup.cfg#L24) and [`pyproject.toml`](https://github.com/bneijt/autotrash/blob/5496bd9fca032b9c2f4329f5c136e2ca13af2b8b/pyproject.toml#L12) indicate that autotrash depends on arrow, but when looking through the source (or grepping `arrow`), it does not appear to be used anywhere. Am I missing something or is the dependency unnecessary?

**Comment by bneijt** [comment]
Fixed, thank you for your help!
