### ISSUE TITLE
DeprecationWarning: SafeConfigParser

### ISSUE THREAD

**Issue by LanceHaverkamp** [bneijt/autotrash#39]
Using Tumbleweed, I'm getting the following warning at the command line:

/usr/bin/autotrash:96: DeprecationWarning: The SafeConfigParser class has been renamed to ConfigParser in Python 3.2. This alias will be removed in future versions. Use ConfigParser directly instead.
  parser = configparser.SafeConfigParser()

**Comment by bneijt** [comment]
That seems like it's probably an older release of autotrash, which I think could be version 0.2:
https://build.opensuse.org/package/show/openSUSE%3AFactory/autotrash

I'm not sure how to upgrade the autotrash package in opensuse, but you could also install autotrash locally for your user using:

`pip install --user autotrash`

**Comment by LanceHaverkamp** [comment]
Thanks!  I've opened a ticket here: [https://bugzilla.opensuse.org/show_bug.cgi?id=1194076](https://bugzilla.opensuse.org/show_bug.cgi?id=1194076)

**Comment by tacerus** [comment]
Hi,
is there a reason `setup.py` was removed with 0.4.2? The Python build macro in RPM relies on it.

**Comment by bneijt** [comment]
There is a setup.py in the source distribution on pypi: https://files.pythonhosted.org/packages/ed/4a/7bc5f24b51d728defeb8e973110cb7574065a17d1504d5a83cf475741f3d/autotrash-0.4.4.tar.gz
The source distribution from github is just a snapshot from the git tree, which is managed via the pyproject.toml file.

**Comment by bneijt** [comment]
Given that there is no response from the last comment, I will assume this issue is closed until further notice. Thank you for taking the time to post an issue!

**Comment by tacerus** [comment]
Apologies @bneijt, I missed your response. It was helpful - thank you very much!
