### ISSUE TITLE
Ubuntu (and Debian? ) install instruction issues

### ISSUE THREAD

**Issue by LanceHaverkamp** [bneijt/autotrash#58]
The installation instructions listed for Ubuntu/Debian no longer work, I believe autotrash has been abandoned by Debian.  `pip install --user autotrash` also no longer works; it fails with a message starting: “This environment is externally managed…” 

The simplest installation I could find is:
$ `sudo apt install pipx`
$ `pipx install autotrash`
$ `autotrash -d 90 --install`

Thanks,
Lance

**Comment by MithicSpirit** [comment]
This seems to be intentional behavior https://github.com/pypa/pip/issues/12085. I think that changing the install instructions to recommend `pipx` is the best way forward.

**Comment by bneijt** [comment]
Just saw that even for Debian we have fallen into the "oldoldstable" suite. Thank you for pointing that out!
