### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by frafra** [bneijt/autotrash#8]
Hi!
0.1.5 is quite old now: why don't you rename the latest version in 0.1.6 and create a new tarball?
This could be useful for non-Debian users, because we don't have docbook-to-man and instant in order to create man pages (which are included only in your release tarball).

Thank you!

**Comment by bneijt** [comment]
Good point! I hope to close this issue together with #9.

**Comment by bneijt** [comment]
With the closing of #9 I created a new release. I also made some documentation changes (build from sgml to markdown) and introduced a new exit status.

Thank you for your encouragement!

**Comment by frafra** [comment]
Thank you for your work :)
